INSERT INTO user_roles
VALUES (1, 'Super Admin', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
       (2, 'Admin', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL),
       (3, 'Customer', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);